version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - APP_PORT=8080
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/bookcabin?sslmode=disable
      - JWT_SECRET=your-secret-key-here-change-in-production
    volumes:
      - ./:/app/src
      - ./data:/app/data
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bookcabin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
